[build]
target = "micro-dev-tools/src/www/index.html"
dist = "micro-dev-tools/.build/dist"

[watch]
watch = ["micro-dev-tools/src/", "tools"]
ignore = ["tools/adjacent-color-checker/.build/dist"]

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["script", "micro-dev-tools/src/.trunk/hooks/post_build"]