name: deploy nightly

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      BRANCH: nightly
    steps:
      - name: checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: restore cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./micro-dev-tools/.build
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: add target
        run: rustup target add wasm32-unknown-unknown
      
      - name: install trunk
        uses: baptiste0928/cargo-install@v1
        with:
          crate: trunk

      - name: install cargo-script
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-script

      - run: trunk build --release --public-url "$REPOSITORY_NAME/$BRANCH/"
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./micro-dev-tools/.build/dist
          publish_branch: pages
          destination_dir: ${{ env.BRANCH }}
          enable_jekyll: false